### ISSUE TITLE
Update newsfeed in GVM without restarting

### ISSUE THREAD

**Issue by duianto** [noidexe/godot-version-manager#31]
The current method for checking if there are new blog posts in GVM, seems to be to restart the app.

The simplest solution might be to add a refresh newsfeed button like there is for the versions dropdown list.

A later enhancement could be to show a message when the button is pressed that says something like: 
- Already viewing the latest blog post
- New blog post(s) found
- or if it's possible to count from the last viewed to the newest: [count] new blog post(s) found

### Timer
Another option could be to use a timer (checked once a day?).

The version list seems to be checked automatically.
Because the latest stable version was 4.1-stable when GVM was minimized (one or two days ago).
Today, when GVM was unminimized, then the latest stable version is 4.1.1-stable.

### New version/post message
Maybe there could be a message/badge/button:
- New version found
- New blog post found
- New version and blog post found

It's probably better to compare the latest dropdown list version with the latest remote version.

Because it could be problematic to check against the latest manually added executable.
It is most likely rare, but if the downloaded Godot executable is renamed with a typo: 4.11 or 44.1
Then there won't be a new version message for a while.

**Comment by noidexe** [comment]
> Because the latest stable version was 4.1-stable when GVM was minimized **_(one or two days ago)._**

👀 I never imagined someone keeping it open for several days. I always shut my computer down at the end of the day 😅

In any case, you are completely right. The news are only updated when it launches. Godot used to at most a couple of blog posts per week, so checking on launch seemed enough.

I requested to the Godot website devs a json version of the news feed, which has everything I need. That means no need to scrape the html for news, no need to fix the scraper if the site structure changes, and a really small download. 

>Another option could be to use a timer (checked once a day?).

Yes I'll implement a timer since it'll avoid cluttering the UI with more buttons.

Regarding any message/bagdes/etc. it is planned for 2.0 to have the app be more aware of the versions you have installed and be able to tell you when minor and patch updates come out.

**Comment by duianto** [comment]
>I always shut my computer down at the end of the day 

Same here, by hibernating, it saves everything in ram to the ssd, so all apps open the same as before shutting down.

**Comment by noidexe** [comment]
Added in 0824737d02301402ad8a7c9d34cb6d5849b3b38f
