### ISSUE TITLE
on macos, clicking "down" on the UI scale feature will crash the application

### ISSUE THREAD

**Issue by cmr624** [noidexe/godot-version-manager#50]
1. Download and run Godot Version Manager v1.16.1 OSX
2. Click the "down" arrow next to UI Scale
3. Observe crash

Using:

macos Ventura 13.2.1 (22D68)

Apple M1 Max

**Comment by shiena** [comment]
When I run it from the command line and click on the scale down button, I get the following error message. It seems that the size of something is set to 0.

```
-[MTLTextureDescriptorInternal validateWithDevice:]:1357: failed assertion `Texture Descriptor Validation
MTLTextureDescriptor has width of zero.
'
```

**Comment by shiena** [comment]
It does not crash when the scale value is changed directly.

**Comment by shiena** [comment]
For some reason, SpinBox.value_changed seems to be called many times on macOS, causing it to go to 0 and crash. As a temporary measure, setting SpinBox.min_value to a value greater than 0 seems to prevent the crash.

**Comment by shiena** [comment]
I think value_changed should be called only once on a mouse click, but value_changed is being called on the frame during mouse down.

**Comment by noidexe** [comment]
Thanks @cmr624 for the report and @shiena for debugging the issue. I've set the minimum value to 0.25 to prevent the crash. What I see is that SpinBox reacts to holding the mouse down and dragging up and down to change the value. This, combined with the UI scaling must be causing problems on OSX. I cannot reproduce it on Windows. Since that's related to the way a native Godot node works it should be reported here: https://github.com/godotengine/godot/issues

**Comment by noidexe** [comment]
> @noidexe I created a new project with Godot 3.5.3 on mac and added SpinBox for verification, but value_changed was called only once when I clicked the up/down button. I wonder why value_changed is called so many times by godot-version-manager.

GVM is not doing anything special other than connecting to value_changed. I suspect what triggers the issue is the resizing of the window. On Windows I see the cursor being repositioned so it's exactly in the same position relative to the SpinBox. It might be that on mac it doesn't happen, and Godot interprets that as a drag motion, which triggers another UI resize, and so on

**Comment by shiena** [comment]
If I comment out the window resize in the UIScale._rescale_ui method, value_changed was called only once.
The window resize did indeed have an effect.
